version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: npm run dev

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "docker"
